[build]
buildCommand = "npm install && npm run install:backend && npm run build:frontend"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "5000" 