[build]
buildCommand = "npm install && npm run install:backend && npm run build:frontend"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "5000" 