services:
  - type: web
    name: sspms-sspms
    env: node
    buildCommand: npm install && npm run build:frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
